### ISSUE TITLE
[WebSocket] Add fully split websocket halves

### ISSUE THREAD

**Issue by r58Playz** [c410-f3r/wtx#275]
Is it possible to add fully split websocket halves similar to [fastwebsockets](https://github.com/denoland/fastwebsockets) [unstable-split](https://github.com/denoland/fastwebsockets/blob/main/src/lib.rs#L389) where the underlying stream is split and any obligated writes (ping/pong) are done through a closure?

I need to be able to concurrently read and write from the websocket, which isn't currently possible as the reader/writer parts need mutable access to the common part.

**Comment by c410-f3r** [comment]
Hello

The upcoming version will introduce owned splits with compression support, which is likely going to happen in the next 2 weeks.

Can you elaborate the need to manually manage pings via a closure? In WTX a received ping is automatically responded with a pong.

**Comment by r58Playz** [comment]
The fastwebsockets split websocket API uses a closure to send pongs back because the split halves are completely separate and cannot communicate internally (at least that's how I understand it). If there is a way to send pongs automatically without locking both the read/write sides for the full duration of the read that's fine too, I only mentioned it as a possible solution for the auto pong replies.

**Comment by c410-f3r** [comment]
Thank you for the clarification. I have always wondered why anyone would want to manually handle pings.

**Comment by r58Playz** [comment]
Hi, I tried using the new wtx 0.25.0 but couldn't as it no longer has `Send` read/write futures because of the `StreamReader`, `StreamWriter`, and `Lock` traits. Is this intended?

**Comment by c410-f3r** [comment]
Hello,

A concurrent client where the owned reader/writer parts are sent to different tasks is available at https://github.com/c410-f3r/wtx/blob/main/wtx-instances/web-socket-examples/web-socket-concurrent-client.rs.

If that is not the desired scenario, can you provide a short snippet about the indented behavior?

**Comment by r58Playz** [comment]
I am trying to use wtx with a trait like this:
```rust
pub trait WebSocketRead: Send {
	fn wisp_read_frame(&mut self) -> impl Future<Output = Result<Bytes, WispError>> + Send;
}
```
I am unable to satisfy the Send bound on the future across any StreamReader/StreamWriter/Lock. Here are my bounds:
```rust
impl<C, NC, SR, SW, const IS_CLIENT: bool> WebSocketRead
	for WebSocketReaderPartOwned<C, NC, SR, IS_CLIENT>
where
	C: Lock<Resource = WebSocketCommonPartOwned<NC, SW, IS_CLIENT>> + Send,
	NC: NegotiatedCompression + Send,
	SR: StreamReader + Send,
	SW: StreamWriter + Send,
	for<'a> C::Guard<'a>: Send,
{
	async fn wisp_read_frame(&mut self) -> Result<Bytes, WispError> {
		let frame = self.read_frame().await;
		// ...
	}
}
```

**Comment by c410-f3r** [comment]
That is an unfortunate outcome originated from the interplay between the current async support in `rustc` and the architectural choices made in `wtx`. As you already mentioned, the root cause is the fact that the compiler can't prove if `StreamReader::read`, `StreamWriter::write_all_vectored` and `Lock::lock` are `Send`.

`wtx` is a `no_std` crate that is not hard-coded to a single runtime like `tokio`, `async-std` or `monoio`. Such a thing provides more flexibility and allows the deploying into embedded devices (https://c410-f3r.github.io/thoughts/securely-sending-dht22-sensor-data-from-an-esp32-board-to-postgresql) but also brings an increased complexity.  That said, it is not possible to directly add `Send` bounds into the `StreamReader`, `StreamWriter` and `Lock` traits, which would make things much easier for you.

For what it is worth, there are two alternatives.

# Concrete type

Use concrete types instead of generic types, this will allow `rustc` to prove the `Send` requirements of the `WebSocketRead::wisp_read_frame` future.

```rust
use std::{future::Future, net::TcpStream};
use tokio::sync::Mutex;
use wtx::{
  misc::{Arc, Lock, StreamReader, StreamWriter},
  web_socket::{
    compression::NegotiatedCompression, WebSocketCommonPartOwned, WebSocketReaderPartOwned,
  },
};

type LocalLock<NC, const IS_CLIENT: bool> = Arc<Mutex<WebSocketCommonPartOwned<NC, LocalWriter, IS_CLIENT>>>; // Or any other thing that implements `Lock`.
type LocalReader = TcpStream; // Or any other thing that implements `StreamReader` like `tokio_rustls::client::TlsStream<T>`.
type LocalWriter = TcpStream; // Or any other thing that implements `StreamWriter` like `tokio::net::tcp::OwnedWriteHalf`.

pub type Bytes = Vec<u8>;

pub enum WispError {}

pub trait WebSocketReadRtn: Send {
  fn wisp_read_frame(&mut self) -> impl Future<Output = Result<Bytes, WispError>> + Send;
}

pub trait WebSocketReadConcreType: Send {
  fn wisp_read_frame(&mut self) -> impl Future<Output = Result<Bytes, WispError>> + Send;
}

impl<NC, const IS_CLIENT: bool> WebSocketReadConcreType
  for WebSocketReaderPartOwned<LocalLock<NC, IS_CLIENT>, NC, LocalReader, IS_CLIENT>
where
  NC: NegotiatedCompression + Send,
  for<'any> NC: 'any,
{
  async fn wisp_read_frame(&mut self) -> Result<Bytes, WispError> {
    let _frame = self.read_frame().await;
    Ok(Bytes::new())
  }
}
```

# Return Type Notation (RTN)

If generic types is a must, then the nightly RTN feature is the only possible way. It seems that it will be stabilized in the next year but I am not totally sure.

```rust
#![feature(return_type_notation)]

use std::{future::Future, net::TcpStream};
use tokio::sync::Mutex;
use wtx::{
  misc::{Arc, Lock, StreamReader, StreamWriter},
  web_socket::{
    compression::NegotiatedCompression, WebSocketCommonPartOwned, WebSocketReaderPartOwned,
  },
};

pub type Bytes = Vec<u8>;

pub enum WispError {}

pub trait WebSocketReadRtn: Send {
  fn wisp_read_frame(&mut self) -> impl Future<Output = Result<Bytes, WispError>> + Send;
}

impl<C, NC, SR, SW, const IS_CLIENT: bool> WebSocketReadRtn
  for WebSocketReaderPartOwned<C, NC, SR, IS_CLIENT>
where
  C: Lock<lock(..): Send, Resource = WebSocketCommonPartOwned<NC, SW, IS_CLIENT>> + Send,
  NC: NegotiatedCompression + Send,
  SR: StreamReader<read(..): Send> + Send,
  SW: StreamWriter<write_all_vectored(..): Send> + Send,
  for<'a> C::Guard<'a>: Send,
{
  async fn wisp_read_frame(&mut self) -> Result<Bytes, WispError> {
    let _frame = self.read_frame().await;
    Ok(Bytes::new())
  }
}
```

After reading https://ntietz.com/blog/rust-needs-a-web-framework-for-lazy-developers/ I got the impression that the majority of companies/individuals prefer libraries/frameworks that allow a quick prototyping of their products/ideas. In this regard `wtx` is probably an awful choice so perhaps you might want to choose other easier/quicker alternatives.
